
export const Routes = {
  Cockpit: { path: "/" },
  Signin: { path: "/login" },
  Signup: { path: "/signup" },
  Verify: { path: "/verify" },
  ForgotPassword: { path: "/forgot-password" },
  ResetPassword: { path: "/reset-password" },
  Export: { path: "/download" },
  PeopleSearch: { path: "/radar/people" },
  PeopleWatchlist: { path: "/radar/people/watchlist" },
  CompanySearch: { path: "/radar/company" },
  CompanyWatchlist: { path: "/radar/company/watchlist" },
  UserProfile: { path: "/profile" },
  Billing: { path: "/billing" },
  Settings: { path: "/settings" },
  ChangePassword: { path: "/change-password" },
  Feedback: { path: "/feedback" },
  Sequences: { path: "/sequences" },
};